services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
